[project]
name = "traffic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.10.1",
    "pytz>=2025.2",
    "requests>=2.32.4",
]
